# Generated by Django 3.1.2 on 2020-10-18 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('text', models.TextField(verbose_name='Содержание')),
                ('date_of_submission', models.DateTimeField(verbose_name='Время отправки')),
                ('priority', models.IntegerField(choices=[(1, 'Неопределен'), (2, 'Низкий'), (3, 'Средний'), (4, 'Высокий'), (5, 'Критический')], default=1, verbose_name='Приоритет заявки')),
                ('status', models.IntegerField(choices=[(1, 'Проверка'), (2, 'Принята'), (3, 'В процессе'), (4, 'Выполнена'), (5, 'В архиве')], verbose_name='Статус заявки')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор заявки')),
            ],
        ),
    ]
