# Generated by Django 3.1.2 on 2020-10-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationmodel',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterField(
            model_name='applicationmodel',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Заголовок'),
        ),
    ]
