# Generated by Django 3.1.2 on 2021-02-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='date_of_submission',
            field=models.DateField(verbose_name='Время отправки'),
        ),
    ]
