# Generated by Django 3.1.2 on 2021-02-20 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210220_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationmodel',
            name='date_of_submission',
        ),
    ]
