# Generated by Django 3.1.2 on 2021-02-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_applicationmodel_date_of_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='date_of_submission',
            field=models.DateField(default='2020-10-18', verbose_name='Время отправки'),
        ),
    ]
