# Generated by Django 3.1.2 on 2021-02-27 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_applicationmodel_date_of_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='responsible_staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL, verbose_name='Отвественный'),
        ),
        migrations.AlterField(
            model_name='applicationmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Автор заявки'),
        ),
    ]
