# Generated by Django 3.1.7 on 2021-04-14 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_chat_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='room',
        ),
        migrations.AddField(
            model_name='chat',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.applicationmodel', verbose_name='Заявка чата'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
