# Generated by Django 3.1.7 on 2021-04-14 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210414_2149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
